### ISSUE TITLE
Biometrics cached and fail after migration

### ISSUE THREAD

**Issue by jaredhasenklein** [TheJumpCloud/jumpcloud-ADMU#104]
I completed a migration using the GUI from a domain-joined profile to a JumpCloud managed profile. The domain joined profile had a fingerprint and face unlock configured through Windows Hello.

After signing in using the password to the JumpCloud profile, there was no sign of biometrics (which is not a problem -- it's easy to readd them). However, I was unable to readd them.

When trying to add a fingerprint or face unlock through Windows settings to the new profile, I received the following error: 
`That fingerprint has already been set up by another account. Try a different finger.`
 When I try to set up facial recognition, I get the message:
`It looks like you've already set up Windows Hello on another account. Remove face recognition from your other account, then try again.`

There are many troubleshooting steps for this issue online and none of them worked.

## Failed troubleshooting steps

- I tried stopping the Windows Biometric Service, clearing the contents of C:\Windows\System32\WinBioDatabase, and restarting the service
- I tried uninstalling the fingerprint and facial recognition drivers from device manager and rebooting the computer
- I tried disabling the fingerprint in bios and reenabling it
- I tried installing updated versions of the fingerprint driver

## Successful troubleshooting
Eventually, I solved the issue with these steps:

1. Open registry editor
2. Navigate to Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList
3. Find the profile with reference to the domain*
4. Delete the key called "GUID"
5. Reboot the computer
6. Try again

*My domain profile was firstl and the new profile is first.last. The profile I found in step 3 was "first.last.DOMAIN" -- a combination of the new username and the domain name.

With those steps, I was able to readd the fingerprint. I'd love to see this fixed before I use the ADMU on more computers. I'm thinking that perhaps all the tool needs to do is remove biometrics before continuing with subsequent steps, so that they are not cached and can be readded.

**Comment by kmaranionjc** [comment]
Hi @jaredhasenklein, I have went through all the steps you provided but can't seem to find the GUID key. Do you have any other tips on trying to remove the fingerprint? I have tried other steps as well including deleting contents in the C:\Windows\.....\NGC folder which supposedly hold the biometrics data. If you have any more info about the registry keys that would be helpful! Thank you!

**Comment by jaredhasenklein** [comment]
Unfortunately I didn't take a screenshot before deleting the key. I can test with another device next week and see if the same steps find it.

Once you're at Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList, are you clicking through each of the profiles? The GUID key only existed in one profile for me (the one which mentioned the AD domain).

**Comment by kmaranionjc** [comment]
@jaredhasenklein we are unable to migrate windows hello biometrics data/can be a complicated process as most fingerprint data are stored in the bios. We recommend to remove it Windows Hello biometrics data prior to migrating a user using the ADMU tool.
