### ISSUE TITLE
GUI and PS script won't work properly on French systems

### ISSUE THREAD

**Issue by vbnin** [TheJumpCloud/jumpcloud-ADMU#21]
Hi there !
I'm using your ADMU tool to migrate my users to JumpCloud, and I noticed that on latest Windows 10 Pro 64 bits in French, they fall in error.
The first error occurs when trying to find OS Architecture, your script expects a "64-bit" variable but my OS sends "64 bits" instead. 
Here is the error : 
`2020-02-26 13:23:49 INFO: Script starting; Log file location: C:\Windows\Temp\jcAdmu.log`
`2020-02-26 13:23:49 INFO: Gathering system & profile information`
`2020-02-26 13:23:53 ERROR: Unknown OSArchitecture`

I changed the expected variables in Functions.ps1 and I was able to pass that one : 
`2020-02-26 16:05:27 INFO: Script starting; Log file location: C:\Windows\Temp\jcAdmu.log`
`2020-02-26 16:05:27 INFO: Gathering system & profile information`
`2020-02-26 16:05:31 INFO: OS: 64 bits`
`2020-02-26 16:05:31 INFO: THIS-COMPUTER is currently Domain joined to ad4s.local`
`2020-02-26 16:05:31 INFO: The secure channel between the local computer and domain is in good condition`

The second one occurs during Loadstate where the user is sent to 'Users' group, but I had to change it for 'Utilisateurs' in Functions.ps1 as well to make the script work.

Here is the error given before translating Users : 
`2020-02-26 16:08:26 INFO: LoadState tool completed for user "AD4S\test.user" converting to "MY-COMPUTER\test.user"`
`2020-02-26 16:08:26 INFO: Adding new user "test.user" to Users group`
`2020-02-26 16:08:29 ERROR: Failed To add new user "test.user" to Users group`

Other than that, thanks for this tool it is making my life much easier !

**Comment by btstevens** [comment]
Hi vbnin,

Please check out the [v1.2.15 release ](https://github.com/TheJumpCloud/jumpcloud-ADMU/releases/tag/v1.2.15). I added a better way to check system architecture and group name  that is not reliant on a language specific string in both the GUI and powershell files.

Please let me know if this resolves your issue.

**Comment by vbnin** [comment]
Hi btstevens,

Thank you very much, I tested the GUI v1.2.15 and it worked !

I guess this issue can be closed now.
