### ISSUE TITLE
Error trying to run gui_jcadmu.exe

### ISSUE THREAD

**Issue by dominicplanview** [TheJumpCloud/jumpcloud-ADMU#32]
While running the ADMU tool (gui_jcadmu.exe)for first time, encountered Error: An unspecified error occurred: error code = 1789

The second time running the tool, I am getting this error message: Failed to compare two elements in the array.

**Comment by btstevens** [comment]
Hello @dominicplanview ,

Can you confirm on the system getting the error the state of the local and domain accounts in 
System Properties --> Advanced System Settings --> User Profiles

Do you see any entries where there is just a SID and no username?

The 1789 error relates to issues translating the SID to a username to display in the GUI. Is there anything different about that account e.g. It is an orphaned account on the system?

![image](https://user-images.githubusercontent.com/35233498/87321004-e7490300-c4e8-11ea-8dd0-64b165d78307.png)

The Second error ' Failed to compare two elements in the array' would also be related to this as another step is to compare the user accounts on the system against the local administrators group to display if it is local admin on the system.

I can work on improving the error catching and display it in a better way. But your help with perhaps how or if there is anything different about the account would be helpful.
