### ISSUE TITLE
Start-Migration ADK/USMT Error

### ISSUE THREAD

**Issue by patlinkit** [TheJumpCloud/jumpcloud-ADMU#50]
Despite performing install of ADK USMT, still encountering the following error when attempting Start-Migration

"2021-03-10 17:57:36 ERROR: Microsoft Windows ADK is installed but User State Migration Tool cant be found - Please correct and Try again."

This is the command I am running, the PC username and domain names are accurate.

`Start-Migration -SelectedUserName 'cdc\marcdemo' -JumpCloudUserName 'marcdemo' -TempPassword '******' -JumpCloudConnectKey '*****************' -AcceptEULA $True -InstallJCAgent $True -LeaveDomain $True -ForceReboot $True -AzureADProfile $False`

[jcadmu.log](https://github.com/TheJumpCloud/jumpcloud-ADMU/files/6119331/jcadmu.log)

**Comment by jworkmanjc** [comment]
Hey @patlinkit,

If you want to use the data copy version of the tool you can run it with the param set like you've pasted in the issue. Have you installed the Windows ADK manually? 

If you want to check out the [convert profile param](https://github.com/TheJumpCloud/jumpcloud-ADMU/wiki/Convert-Profile), it'll be a much faster account conversion which doesn't rely on the USMT/ Windows ADK.

An example of invoking this on a system [is provided here](https://github.com/TheJumpCloud/jumpcloud-ADMU/blob/master/jumpcloud-ADMU-Advanced-Deployment/InvokeFromAgent/Invoke%20ADMU.ps1#L26)

**Comment by patlinkit** [comment]
> Hey @patlinkit,
> 
> If you want to use the data copy version of the tool you can run it with the param set like you've pasted in the issue. Have you installed the Windows ADK manually?
> 
> If you want to check out the [convert profile param](https://github.com/TheJumpCloud/jumpcloud-ADMU/wiki/Convert-Profile), it'll be a much faster account conversion which doesn't rely on the USMT/ Windows ADK.
> 
> An example of invoking this on a system [is provided here](https://github.com/TheJumpCloud/jumpcloud-ADMU/blob/master/jumpcloud-ADMU-Advanced-Deployment/InvokeFromAgent/Invoke%20ADMU.ps1#L26)

Many thanks! 

I'm working on automating the PS Remoting prep since we don't often encounter existing GP structures, I gotta make the changes manually on the workstations. 

I'll be speaking with a JumpCloud engineer soon regarding the Start-Migration error I had to begin with. I did install USMT manually, I even put the silent install of ADK in my script with the USMT and Deployment Tools features only. I get this error on two separate systems, one Dell laptop and another Virtual Machine. I suspect I might have to use an older ADK, but not sure how to rollback an updated ADK on a system I might be deploying to so I'd rather go with your provided solution anyways. This will help us with future clients, too.

**Comment by patlinkit** [comment]
I've discovered the "Enable-PSRemoting" module which will do this for me instead of GPO or making my own module.

Can I run this discovery/migration script from any device on the domain with domain admin rights, or should I only be running these from the DC?
