### ISSUE TITLE
wmic command line tool is no longer present from Windows 21H1 onwards

### ISSUE THREAD

**Issue by willemkokke** [TheJumpCloud/jumpcloud-ADMU#67]
It's only used to get the system drive, and the powershell equivalent is trivial.

I ran into this when migrating a Windows 11 Insider build.
I appreciate that that is probably an unsupported configuration, however migration worked great after my fix 💯 

I’ll create the trivial pull-request now.

**Comment by jworkmanjc** [comment]
Hi @willemkokke, thanks for the PR, I'll need to bump the version and do a few other things to the PR but I should be able to work on this sometime in the next two weeks. I appreciate you digging in and submitting a fix!

**Comment by willemkokke** [comment]
Thanks! It was a fun diversion. There is no rush on our behalf. It was the only windows 11 machine we had, and upgrades to windows 11 are now blocked using Jumpcloud 😂
